[package]
name = "friday-assistant"
version = "0.1.0"
edition = "2021"

[dependencies]
hyper = "0.14.24"
lambda_runtime = "0.7.3"
serde = "1.0.152"
serde_derive = "1.0.152"
serde_json = "1.0.93"
tokio = "1.25.0"
