apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday-secret-manager
spec:
  replicas: 1
  revisionHistoryLimit: 5 # Manter apenas 5 versões antigas para rollback
  selector:
    matchLabels:
      app: friday-secret-manager
  template:
    metadata:
      labels:
        app: friday-secret-manager
    spec:
      containers:
      - name: friday-secret-manager
        image: z33p/friday-secret-manager:2026-04-02.v1
        resources:
          requests:
            cpu: "10m"
            memory: "10Mi"
          limits:
            cpu: "30m"
            memory: "20Mi"
