apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-proxy
  namespace: default
  labels:
    app: nginx-proxy
spec:
  selector:
    matchLabels:
      app: nginx-proxy
  template:
    metadata:
      labels:
        app: nginx-proxy
    spec:
      initContainers:
      - name: config-init
        image: alpine:latest
        command: ["/bin/sh", "-c"]
        args:
        - |
          apk add --no-cache gettext
          envsubst '${FRIDAY_MCP_API_KEY} ${AUTHORIZED_IP}' < /templates/nginx.conf > /config/nginx.conf
        env:
        - name: FRIDAY_MCP_API_KEY
          valueFrom:
            secretKeyRef:
              name: friday-mcp-proxy
              key: INTERNAL_SIGNATURE
        - name: AUTHORIZED_IP
          valueFrom:
            secretKeyRef:
              name: friday-mcp-proxy
              key: AUTHORIZED_IP
        volumeMounts:
        - name: nginx-config-template
          mountPath: /templates
        - name: nginx-config-final
          mountPath: /config
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
          hostPort: 80
        - containerPort: 443
          hostPort: 443
        volumeMounts:
        - name: nginx-config-final
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: ssl-certs
          mountPath: /etc/letsencrypt
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: nginx-config-template
        configMap:
          name: nginx-config
      - name: nginx-config-final
        emptyDir: {}
      - name: ssl-certs
        hostPath:
          path: /etc/letsencrypt
          type: Directory
      tolerations:
      - operator: Exists
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-proxy-service
  namespace: default
spec:
  selector:
    app: nginx-proxy
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  type: ClusterIP