version: '3.8'
services:
  newsletter-sagas:
    build:
      context: .
      dockerfile: NewsletterSagas/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=PROD

  friday-message-broker:
    build:
      context: .
      dockerfile: FridayMessageBroker/Dockerfile
    environment:
      - DOTNET_ENVIRONMENT=PROD
