apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday-newsletter-sagas
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friday-newsletter-sagas
  template:
    metadata:
      labels:
        app: friday-newsletter-sagas
    spec:
      containers:
      - name: friday-newsletter-sagas
        image: z33p/friday-docker-hub:newsletter-sagas
        resources:
          limits:
            cpu: "0.5"
            memory: "128Mi"
        env:
        - name: DOTNET_ENVIRONMENT
          value: "PROD"
