apiVersion: v1
kind: Service
metadata:
  name: friday-secret-manager-service
spec:
  selector:
    app: friday-secret-manager
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
