apiVersion: apps/v1
kind: Deployment
metadata:
  name: friday-secret-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: friday-secret-manager
  template:
    metadata:
      labels:
        app: friday-secret-manager
    spec:
      containers:
      - name: friday-secret-manager
        image: z33p/friday-secret-manager:v1.0.0
        resources:
          requests:
            cpu: "10m"
            memory: "16Mi"
          limits:
            cpu: "50m"
            memory: "64Mi"
        env:
        - name: IS_PROD
          value: "true"
