apiVersion: rabbitmq.com/v1beta1
kind: RabbitmqCluster
metadata:
  name: friday-rabbitmq
spec:
  replicas: 1
  resources:
    requests:
      cpu: "20m"
      memory: "500Mi"
    limits:
      cpu: "150m"
      memory: "500Mi"