# This is a basic workflow to help you get started with Actions

name: FridayGoogleOauth

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [master]
    paths:
      - serverless/friday-google-oauth/**
      - .github/workflows/friday-google-oauth.yml
  pull_request:
    branches: [master]
    paths:
      - serverless/friday-google-oauth/**
      - .github/workflows/friday-google-oauth.yml

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  FridayGoogleOauth:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./serverless/friday-google-oauth
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Zip Build Files
        run: cd dist && zip main.zip *

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1  # Substitua pela sua região AWS

      - name: Deploy to AWS Lambda
        run: aws lambda update-function-code --function-name friday-google-oauth --zip-file fileb://dist/main.zip

